"""NumPy 2.x + PyTorch 2.6 compatibility shims for RecBole.

RecBole's ``Config.compatibility_settings()`` (recbole/config/configurator.py)
unconditionally evaluates ``np.float_``, ``np.complex_``, ``np.object_``,
``np.unicode_``, ``np.str_`` to restore deprecated aliases. NumPy 2.0 removed
those right-hand-side names, so the line raises ``AttributeError`` before any
of our code gets to run.

We pre-populate the missing attributes on the ``numpy`` module. RecBole's
subsequent assignments (``np.float = np.float_`` etc.) then succeed and behave
identically to the old NumPy 1.x path.

Import this module **before** anything that imports ``recbole``.
"""

from __future__ import annotations

import numpy as np

_aliases = {
    "float_": np.float64,
    "complex_": np.complex128,
    "object_": object,
    "unicode_": np.str_,
    "bool_": np.bool_,
    "int_": np.int64,
}

for _name, _val in _aliases.items():
    if not hasattr(np, _name):
        setattr(np, _name, _val)


# --- PyTorch 2.6: torch.load default flipped to weights_only=True ---------
# RecBole checkpoints embed non-tensor objects (Config, Dataset metadata) that
# the safe unpickler refuses with "Unsupported operand ..." errors. Since these
# checkpoints are generated by our own training runs, we restore the legacy
# default so trainer.evaluate(..., load_best_model=True) can load them.
import torch as _torch  # noqa: E402

if not getattr(_torch.load, "_recbole_weights_only_patched", False):
    _orig_torch_load = _torch.load

    def _patched_torch_load(*args, **kwargs):  # type: ignore[no-redef]
        kwargs.setdefault("weights_only", False)
        return _orig_torch_load(*args, **kwargs)

    _patched_torch_load._recbole_weights_only_patched = True  # type: ignore[attr-defined]
    _torch.load = _patched_torch_load  # type: ignore[assignment]
